apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wahlergebnisse
  name: wahlergebnisse-poller
spec:
  template:
    spec:
      containers:
        - name: wahlergebnisse
          env:
            - name: WAHLEN_DEMO
              value: "1"
            - name: WAHLEN_DEMO_ZYKLUS
              value: "3600"
            - name: PUBLIC_SITE_URL
              value: https://demo.wahlergebnisse.levinkeller.de
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wahlergebnisse
  name: wahlergebnisse
spec:
  template:
    spec:
      containers:
        - name: wahlergebnisse
          env:
            - name: WAHLEN_DEMO
              value: "1"
            - name: PUBLIC_SITE_URL
              value: https://demo.wahlergebnisse.levinkeller.de
