apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wahlergebnisse-demo
resources:
- ../../base
- openai.sealed.yaml
patches:
- path: demo-env.yaml
- path: ingress.yaml
- path: ohne-export-token.yaml
images:
- name: ghcr.io/levino/wahlergebnisse
  newName: ghcr.io/levino/wahlergebnisse
  newTag: 6ff1dfdd33ee074b9cb48bfacf236658f94e5499
