apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wahlergebnisse-demo
resources:
- namespace.yaml
- ../../base
- openai.sealed.yaml
patches:
- path: demo-env.yaml
- path: ingress.yaml
- path: ohne-export-token.yaml
images:
- name: ghcr.io/levino/wahlergebnisse
  newName: ghcr.io/levino/wahlergebnisse
  newTag: 6c6814d0bdd7a35c00f0cd795e30d1cc784049b9
