apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wahlergebnisse-demo
resources:
- namespace.yaml
- ../../base
- openai.sealed.yaml
patches:
- path: demo-env.yaml
- path: ingress.yaml
- path: ohne-export-token.yaml
images:
- name: ghcr.io/levino/wahlergebnisse
  newName: ghcr.io/levino/wahlergebnisse
  newTag: 906281713f1b916abe97e7a770c7cfe71ab0bc3c
