---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wahlergebnisse-openai
  namespace: wahlergebnisse-demo
spec:
  encryptedData:
    token: AgAeezAUTHLJJddRfwvYeMrRmNKycAwGO2YwKwLLKwbuI3HJGTfj4hzC7+X6TA+/PSz4vcJRYBRjo53IrGC7rLlC1/CPUoRFMlUtk3419gr1AnFQLdSXc+l+yUevyanWO9Yam7XKsiCxmuI2XXSzqDSaA7R9JZ+G0M4lk3T/BklHHsaCnGQvzvdEdYK8PEtE9IgDxCHonNFc/s3btQnLOwUycKbbjyr4l/dcCzZ16a/b/DACz1wvI42JpclCPUYj4Ffl9rlwiIqv/cNR3+hMp2ud0nGmMV2CU8t075EU1JfG7AlqXJXh6mbwffCAIWb+Bo/VJja26jplUD0IiSZbNYfIL0izzS03AIdD7HeO7u3z2v2aryE501tmk8ETjPbVuKgX2EdxfPNW130frzAoUGJqaybWv6eyHmm2x7nKrn81BLXArmcAs6kp7GE23LZrUhAWva4wBIJ2OImuk8rgkihl4RYfGViFNVuOAvfZTGJZEKlRx5yvE0bFtfz6oKzBeTrRAZtMlq/Jdaj+fz43Z/ItNpEhftnV9CrPxwhUl5WuESasQzW1BHfZJ/Isv7n2TYDWJEtVDyu5HHoME0tTQUAzXGAC/o7yodiU2rMM8jzCrQpSq0aQBDCjzHfRMv21sLPrQMJP/RXaM81OfDEywmcRgamIsG0iAC+0v37A87UdPetJrcUwxjkFVSMnMhNf6idyK21puygfvAVgnaD9M1FReYTvX7cgZJ4JDZx3k9RkgOzVOvegKbLxJtf2A3oPOSsw9rNIx2aFqE1bnrMwpdmJ8/oMPU3vNxPWqXY4hwReOK7XK0CMbgDcftsMvMpp6SPs46Fx+9UBDGzRPtKgzB9sRqJgHb/32anDvzftFt8V98Ahox4Qs4q5j1KDx7EKQBkCNJTd2PbrsEqyebzW9qzAf2Upww==
  template:
    metadata:
      creationTimestamp: null
      name: wahlergebnisse-openai
      namespace: wahlergebnisse-demo
