apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wahlergebnisse
resources:
  - pvc.yaml
  - deployment-poller.yaml
  - deployment-web.yaml
  - service.yaml
  - ingress.yaml
  - export-token.sealed.yaml
