apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wahlergebnisse
resources:
- ../../base
- openai.sealed.yaml
images:
- name: ghcr.io/levino/wahlergebnisse
  newName: ghcr.io/levino/wahlergebnisse
  newTag: 5228b9cb12c330e3b90a474ad861edf8da3efa6d
