---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wahlergebnisse-openai
  namespace: wahlergebnisse
spec:
  encryptedData:
    token: AgBd4dL8EnZM6uePyeAkmJUYlQk9SyAynFvnwQEUoKV/wvXexoxO2zQkj1BT2mb0R3rcpIxAByhqfBS12iBoZJuH5Ygc6krV5QIHWyJUDd3dm7TeMcMZnFK52XRJT4ZGWwZ4UquiwzME8WDNTARNikpbxN1714seWAarEh5yUjpwSiQ39qDmFs/oiC8v5x9vuzxN89Ts3jM8IFJsaL7h/+G6j8M06r/LXdtQXZkviBE/QLa8L9O7sIaSzmrOcv8sjcI2leqZr0syxvXoVdHejqSqe67DbL2qPtxyDw4KT6Fcjw4pKraJoq42UqxngEQl7hpeTHkDYg+j1VxPQJV2o0zzziD/9WFpX1lU87g0LG4ATIbBvwrq0AiDD2HxN0WnhwDuby4l1GuuHaIWnrbO9wbcU/W70OQnskDn8HM7vdTsGUES5xetADDmVs6gkIx4CF+D9WQ2HjZu6uwdYUmtJNEzu2JtQnHsEVAaUKg1OmOZxIjFCHBrPdAtVMm4KMkBkqqmHn73ItbUh0lK4XzGmfU6t5DLjpDkXeDSPlW60qm29qVzyXQaCG4xUxMXdVdFxP/DCsiOusdzISA8ZhrEKCCrQcJNPuuM1aRd0NJ20sY1RSdHJYRZclLpmqyBbLQ09T3LXTANobsZnlwAJr5WoGyQoyIyMhZBGx2FkAw8e09Ps/Hk48OoLms21N7lW+E+fV7MUE2l78HSlqNA32P7G5St0BaJzfMjYmTrBo/y3B+cAzvC6fbqMMZUOyPOUSxd+qtqRKtciUpqoMA9ybGPzop2SWehUaGhLPbk7WNihAlBg/sjnmVutf6QCXKk89Dkq7KEvU4CcwXk0TY4IXSuQVKsteEgYsasNoJqAagdpCCmmbHBt/dql8y8y9pbk+jMKCsot2j4ilB5ULkM6UhdKldicpv9wg==
  template:
    metadata:
      creationTimestamp: null
      name: wahlergebnisse-openai
      namespace: wahlergebnisse
